version: '3'

services:
  redis-master:
    image: redis:4-alpine
    networks:
      - dbnet
  redis-slave:
    image: redis:4-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    networks:
      - dbnet
  sentinel:
    build: sw-node-1:5000/redis-sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - REDIS_MASTER=redis-master
    links:
      - redis-master
      - redis-slave
    networks:
      - dbnet
      - appnet

networks:
  dbnet:
    external: true
  appnet:
    external: true