version: '3.3'

services:
  proxy:
    image: perconalab/proxysql
    networks:
      - dbnet
      - appnet
    ports:
      - "3306:3306"
      - "6032:6032"
    env_file: .env
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == sql-proxy
  xtradb:
    image: perconalab/percona-xtradb-cluster:latest
    env_file: .env
    networks:
      - dbnet 
    ports:
      - "3306"
    volumes:
      - /var/lib/mysql
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.labels.type == database

networks:
  dbnet:
    external: true
  appnet:
    external: true