version: "3"

services:
  nginx:
    image: daper/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - frontnet
      - appnet

networks:
  frontnet:
    external: true
  appnet:
    external: true